### PR TITLE
Insure fully qualified image URLs

### PR DESCRIPTION
**Pull request by dguillory**
Because relative image URLs throw errors in Facebook Open Graph and Google structured data tests, I added a helper function to insure fully qualified URLs, and applied to all image meta.

### CODE REVIEW

**Comment by khalwat** [comment]
How could we end up with a non-fully qualified URL?  Only way I can think of is if the site is misconfigured without asset URLs?

**Comment by dguillory** [comment]
Local folder asset URLs can be relative (e.g. /assets/general/).

**Comment by khalwat** [comment]
You're right, I probably should handle that case.  It needs to be done a little differently to ensure that it works with localized sites, though.  I think I might make it "automagic" so that it just does it for things that must be full URLs.

**Comment by dguillory** [comment]
Makes sense, I hadn't even considered localized sites. So, the way you're thinking, if I set the image dynamically to something relative like this…

```
{% set seoImage = "/assets/seo-image.jpg" %}

{% set seomaticMeta = seomaticMeta | merge({
    'seoImage': seoImage,
    'twitter': seomaticMeta.twitter | merge({'image': seoImage}),
    'og': seomaticMeta.og | merge({'image': seoImage})
}) %}
```

…would that automagically output fully qualified URLs, or would it need to be addressed when setting the seoImage variable, like with a helper function?

By the way, thanks a ton for this plugin, it's been a godsend. Really appreciate all of the effort.

**Comment by khalwat** [comment]
Here's what I ended up with:

```
    public function getFullyQualifiedUrl($url)
    {
        $result = $url;
        $srcUrlParts = parse_url($result);
        if (($srcUrlParts['scheme']) && ($srcUrlParts['host']))
        {
    /* -- The URL is already a fully qualfied URL, do nothing */
        }
        else
        {
            $siteUrl = craft()->getSiteUrl();
            $urlParts = parse_url($siteUrl);
            if (($urlParts['scheme']) && ($urlParts['host']))
                $siteUrl = $urlParts['scheme'] . "://" . $urlParts['host'] . "/";
            else
                $siteUrl = "/";
            if (($siteUrl[strlen($siteUrl) -1] == '/') && ($result[0] == '/'))
            {
                $siteUrl = rtrim($siteUrl, '/');
            }
            $result = $siteUrl . $result;
        }

        return $result;
    } /* -- getFullyQualifiedUrl */
```

**Comment by khalwat** [comment]
As for your question, so a basic tenet of the way SEOmatic works is that it does all sorts of magic behind the scenes, but once the variables hit the templates, it doesn't mess with them further.

The only exception to this is that it _does_ sanitize your input in terms of trimming it appropriately, making sure it's properly HTML-escaped, etc.

So if you set it the way you're setting it above, it's not going to change it to be a fully qualified URL.  I suppose I can expose the function via a variable if you think that'd be helpful.

**Comment by khalwat** [comment]
I pushed it to `develop` if you want to check it out?  I added a helper twig filter/function and variable: `getFullyQualifiedUrl()` as well as it does it automatically for the canonicalUrl, seoImage, and anything with a key of `url` 

https://github.com/nystudio107/seomatic/tree/develop

**Comment by dguillory** [comment]
Awesome, I'll check it now, thanks.

**Comment by dguillory** [comment]
seomaticMeta.seoImage is working like a charm, but some of the others don't seem to be (I've checked seomaticSiteMeta.siteSeoImage and seomaticIdentity.image so far).

**Comment by khalwat** [comment]
Try a pull now.  I think I got all of the cases:

https://github.com/nystudio107/seomatic

**Comment by dguillory** [comment]
Yep, that's it. I've tested it against a couple of dev sites with sitewide defaults, entry overrides, and dynamic template overrides with `getFullyQualifiedUrl()` and everything is working perfectly. Thanks so much!

**Comment by khalwat** [comment]
Great, thanks for your suggestions, and the pull request!

**Pull request closed without merging**
