### PR TITLE
prevent errors on Dashboard by rendering field only in single-entry context

### PR DESCRIPTION
**Pull request by intoeetive**

### CODE REVIEW

**Comment by khalwat** [comment]
How are errors generated?  Trying to replicate it

**Comment by intoeetive** [comment]
Without this fix, whenever I access Dashboard I get `Trying to get property of non-object` referencing this line in `Seomatic_MetaFieldType.php`
`$fieldData = array('title' => $this->element->content['title']);`

**Comment by intoeetive** [comment]
Separate, but related issue: with latest release, when creating new field I get
`Variable "element" does not exist` in `/craft/plugins/seomatic/templates/field_settings.html(3)`

**Comment by khalwat** [comment]
There is no `field_settings.html` in the current release... is there a chance you could have merged the current release with the previous release?  Please see here:

https://github.com/nystudio107/seomatic/issues/21

**Comment by intoeetive** [comment]
You-re right, the template error is because I kept old template files.

However the first Dashboard issue is still there, as it's not template-related

**Comment by khalwat** [comment]
Got it, thanks, merging!

**Comment by OezlemYi** [comment]
Wondering, because I get still errors..
Maybe a few infos: I use plesk server with PHP 7.1.12. The error is showing when I want to analysis the SEOmetrics Content. 
But the error is also showing with PHP 5.6. Any ideas?

bildschirmfoto 2017-12-12 um 16 00 12
bildschirmfoto 2017-12-12 um 16 00 17
bildschirmfoto 2017-12-12 um 16 00 24

**Comment by khalwat** [comment]
So that's an error because it can't find a `<title>` tag on the page. I should probably safeguard against this, but if you're using SEOmatic, I'm not sure how you could _not_ have a `<title>` tag on there?

**Pull request merged**
